In [1]:
import numpy as np

In [3]:
np.random.rand()

0.24001624612719685

In [4]:
np.random.rand(10)

array([0.81024799, 0.86459138, 0.14555119, 0.72095874, 0.50692205,
       0.85460833, 0.85366789, 0.04980211, 0.84574138, 0.6895022 ])

In [5]:
np.random.randn() #normal distribution

0.2455072116164883

In [6]:
np.random.randn(10) 

array([-0.58023872, -1.79841618, -0.12791571, -0.41698935, -0.58343078,
        0.0648273 , -0.38624761, -2.87777264,  0.67748612, -0.81686069])

In [8]:
np.random.randint(1,10,10) #int

array([8, 3, 6, 8, 3, 7, 7, 3, 8, 5])

In [10]:
ar = np.random.randint(1,100,25)
ar

array([ 2, 66, 81, 78, 94, 54, 17, 37, 14, 46, 93, 16, 62, 74, 90, 16, 16,
       64, 47, 93, 32, 94, 57,  3, 10])

In [11]:
ar.shape

(25,)

In [13]:
ar = ar.reshape(5,5)
ar

array([[ 2, 66, 81, 78, 94],
       [54, 17, 37, 14, 46],
       [93, 16, 62, 74, 90],
       [16, 16, 64, 47, 93],
       [32, 94, 57,  3, 10]])

In [14]:
ar.shape

(5, 5)