In [1]:
import numpy as np

In [3]:
ar = np.arange(10, 20)
ar

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [5]:
ar[0], ar[8]

(10, 18)

In [8]:
ar[3:6]

array([13, 14, 15])

In [11]:
ar[:3] = [11, 22, 33]
ar

array([11, 22, 33, 13, 14, 15, 16, 17, 18, 19])

In [12]:
ar = 100
ar

100

In [16]:
ar = np.arange(10, 20)
ar[:] = 100
ar

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [19]:
ar = np.arange(10, 20)
ar2 = ar[:3]
ar2

array([10, 11, 12])

In [20]:
ar2[0] = 99
ar2

array([99, 11, 12])

In [22]:
ar #ar also change

array([99, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
ar = np.arange(10, 20)
ar2 = ar[:3].copy()
ar2[0] = 99
ar2

array([99, 11, 12])

In [29]:
ar # will still the same

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [32]:
ar2d = np.arange(12).reshape(4,3)
ar2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [35]:
ar2d[1] #2nd row

array([3, 4, 5])

In [37]:
ar2d[1][1] #2nd row and 2nd column

4

In [38]:
ar2d[1,1]

4

In [40]:
ar2d[:,1]

array([ 1,  4,  7, 10])

In [43]:
ar2d[0:2, 1:3]

array([[1, 2],
       [4, 5]])

In [44]:
ar2d[:2, 1:]

array([[1, 2],
       [4, 5]])

In [45]:
ar = np.arange(10, 20)
ar

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [46]:
np.greater(ar, 15)

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [49]:
ar2 = ar > 15
ar

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [51]:
ar[ar2]
#ar[ar > 15]

array([16, 17, 18, 19])