In [2]:
import numpy as np

In [3]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
ar = np.array(l)

In [10]:
ar.shape

(3, 3)

In [14]:
np.zeros((3,3), dtype=np.int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [15]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
ar.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [19]:
ar.reshape(2,5)

ValueError: cannot reshape array of size 9 into shape (2,5)